export default{
    name:'works',
    title:'Works',
    type:'document',
    fields:[
        {
            name:'title',
            title:'Title',
            type:'string',
        },
        {
            name:'description',
            title:'Description',
            type:'string',
        },
        {
            name:'projectLink',
            title:'Project Link',
            type:'string',
        },
        {
            name:'codeLink',
            title:'Code Link',
            type:'string',
        },
        {
            name:'videoLink',
            title:'Video Link',
            type:'string',
        },
        {
            name:'duration',
            title:'Duration',
            type:'string',
        },
        {
            name:'category',
            title:'Category',
            type:'string',
        },
        {
            name:'imgUrl',
            title:'ImgUrl',
            type:'image',
            options:{
                hotspot:true,
            },
        },
        {
            name:'tag',
            title:'Tag',
            type:'array',
            of: [
                {
                    name:'tag',
                    title:'Tag',
                    type:'string',
                }
            ]
        },
        {
            name:'ingredient',
            title:'Ingredient',
            type:'array',
            of:[
                {
                    name:'ingredient',
                    title:'Ingredient',
                    type:'string',
                }
            ]
        },
    ],
};